bezirke = ['CharlottenburgNord', 'Malchow', 'Altglienicke', 'Adlershof', 'Dahlem', 'Tiergarten', 'Hansaviertel',
           'FalkenhagenerFeld', 'Wilhelmstadt', 'Rahnsdorf', 'Tegel', 'Rosenthal', 'Britz', 'AltTreptow',
           'Charlottenburg', 'Heiligensee', 'Mitte', 'Buckow', 'Kreuzberg', 'Zehlendorf', 'Gesundbrunnen', 'Wannsee',
           'Nikolassee', 'Luebars', 'Haselhorst', 'Koepenick', 'Buckow2', 'Baumschulenweg', 'Wedding', 'Gruenau',
           'Blankenburg', 'Lichtenberg', 'Karlshorst', 'PrenzlauerBerg', 'Pankow', 'Bohnsdorf', 'Hermsdorf', 'Lankwitz',
           'Wartenberg', 'Plaenterwald', 'Neukoelln', 'Wilmersdorf', 'Moabit', 'Hakenfelde', 'Rudow', 'Marienfelde',
           'Wittenau', 'Reinickendorf', 'Kladow', 'Grunewald', 'Niederschoeneweide', 'Karow', 'Friedrichshain',
           'FranzoesischBuchholz', 'Frohnau', 'Mueggelheim', 'Niederschoenhausen', 'Oberschoeneweide', 'Lichterfelde',
           'Mariendorf', 'Wilhelmsruh', 'Konradshoehe', 'Biesdorf', 'Rummelsburg', 'Lichtenrade', 'Westend',
           'Waidmannslust', 'Halensee', 'Friedrichshagen', 'Buch', 'MaerkischesViertel', 'Falkenberg', 'Fennpfuhl',
           'Gropiusstadt', 'Tempelhof', 'NeuHohenschoenhausen', 'Blankenfelde', 'Johannisthal', 'Friedenau',
           'Heinersdorf', 'Gatow', 'Mahlsdorf', 'Hellersdorf', 'Kaulsdorf', 'Marzahn', 'Friedrichsfelde',
           'AltHohenschoenhausen', 'Weissensee', 'Steglitz', 'Spandau', 'Staaken', 'Schmoeckwitz', 'Schoeneberg',
           'Schmargendorf', 'Siemensstadt']

known_locations = {
    'ostbahnhof': 'Friedrichshain',
    'görli': 'Kreuzberg',
    'monbijoupark': 'Mitte',
    'saatwinklerdamm': 'Charlottenburg Nord',
    'olympiastadion': 'Westend',
    'kudamm': 'Charlottenburg',
    'fhain': 'Friedrichshain',
    'fehrbellinerpatz': 'Wilmersdorf',
    'ubhfkleistpark': 'Schöneberg',
    'savignyplatz': 'Charlottenburg',
    'hermannplatz': 'Neukölln',
    'schlachtensee': 'Zehlendorf',
    'sachsendamm': 'Schöneberg',
    'oberbaumbruecke': 'Kreuzberg',
    'oberbaumbrücke': 'Kreuzberg',
    'kotti': 'Kreuzberg',
    'ostkreuz': 'Friedrichshain',
    'alex': 'Mitte',
    'kulturbrauerei': 'Prenzlauer Berg',
    'xberg': 'Kreuzberg',
    'alexanderplatz': 'Mitte',
    'messedamm': 'Westend',
    'humboldthain': 'Gesundbrunnen',
    'pberg': 'Prenzlauer Berg',
    'prenzelberg': 'Prenzlauer Berg',
}

